##
# Update the APT package cache and install packages as a root user
##
--
- name: Install packages
- hosts: all
  tasks:
    - name: Install required packages
      apt:
        name: "{{ packages }}"
      become: yes
      vars:
        packages:
        - vim
        - fail2ban
        - python3-devel
        - python-virtualenv
        - python3-virtualenv
        - python-devel
        - gcc
        - libselinux-python
        - redhat-rpm-config
        - libtiff-devel
        - libjpeg-devel
        - libzip-devel
        - freetype-devel
        - lcms2-devel
        - libwebp-devel
        - tcl-devel
        - tk-devel
        - policycoreutils-devel
